# Generated by Django 2.1.7 on 2021-03-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210312_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_limit',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='page',
            name='title_limit',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='page',
            name='url_limit',
            field=models.IntegerField(default=200),
        ),
    ]
